# SwiftLint Configuration for Cashin'
# This file configures SwiftLint rules for the project

# Paths to include/exclude during linting
included:
  - CashinApp.swift
  - Models
  - Views
  - Managers
  - Extensions
  - Tests

excluded:
  - Pods
  - .build
  - DerivedData
  - Resources/Assets.xcassets

# Disable specific rules
disabled_rules:
  - trailing_whitespace
  - line_length # Can be adjusted based on team preference

# Opt-in rules (enable additional rules)
opt_in_rules:
  - empty_count
  - explicit_init
  - closure_spacing
  - contains_over_first_not_nil
  - empty_string
  - explicit_self
  - fatal_error_message
  - file_header
  - first_where
  - sorted_imports
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces

# Rule configurations
line_length:
  warning: 120
  error: 150
  ignores_comments: true
  ignores_urls: true

file_length:
  warning: 500
  error: 1000

function_body_length:
  warning: 50
  error: 100

type_body_length:
  warning: 300
  error: 500

identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 50
    error: 60
  excluded:
    - id
    - URL
    - url

type_name:
  min_length: 3
  max_length: 50

cyclomatic_complexity:
  warning: 10
  error: 20

nesting:
  type_level: 2

# Custom rules
custom_rules:
  # Ensure proper spacing after MARK comments
  mark_spacing:
    name: "MARK Spacing"
    regex: '\/\/ MARK: -[^ ]'
    message: "MARK comments should have a space after the dash (// MARK: - Text)"
    severity: warning

# Reporter type
reporter: "xcode"
